site_name: Dokumentationen



copyright: Copyright &copy; 2024 schlumberger digital e.K. 

theme:
    name: 'material'
    language: de
    palette:
        primary: white
        accent: deep purple
    logo: "96-quer-schlumberger-digital-logo.png"
    favicon: Favicon SD.jpg
    features:
        - navigation.sections
        - navigation.path
        - navigation.instant
        - navigation.tabs
        - content.code.copy
plugins:
    - search
    - offline

extra:
    generator: false
    social:
        - icon: material/monitor
          link: https://www.schlumberger.digital
        - icon: fontawesome/regular/envelope
          link: mailto:support@schlumberger.digital
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets